kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:  #labels are used as selectiors
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: labels
  labels:
    project: expense
    environment: dev
    component: backend
    version: "1.0.0"
spec:
  containers:
  - name: nginx
    image: nginx            