
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # labels of deployment resource
  labels:
    app: nginx
    tier: frontend
    purpose: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      purpose: deployment
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        purpose: deployment
  #this is manifest file      
    spec:
      containers:
      - name: nginx
        image: hussainbi/deployment:2.0.0
        ports:
        - containerPort: 80
---
kind: Service  # to run the service on internet we are using LoadBalancer
apiVersion: v1
metadata:
  name: nginx  # corrected this line
spec:
  type: LoadBalancer
  selector:  # labels are used as selectors
    app: nginx
    tier: frontend
    purpose: deployment
  ports:
  - protocol: TCP
    port: 80  # service port
    targetPort: 80
    nodePort: 30007
